Задание 1
AHDEPCEH/Robots_JavaProject pull request #1
Opened 2024-02-26 15:45 UTC by AHDEPCEH

Переделал процесс закрывания окна, сделал небольшой рефакторинг и сделал проект на архитектуре maven

2024-02-26 19:05 UTC, vpyzhyanov requested changes
Решение самой задачи - хорошее. Но вот ООП что-то пострадало. Понятность кода наоборот упала.

2024-02-26 19:05 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +        menuBar.add(windowMenu);
А какое бы вы написали замечание в этой строчке?

2024-02-27 09:04 UTC, AHDEPCEH commented
Я исправил все замечания, включая последнее - некорректное имя переменной

2024-02-28 19:28 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +        initJMenuBar(new JMenuBar());
для чего вы передаёте сюда этот класс? Спойлер: смысла в этом нет никакого, создавайте его прямо в методе.

2024-02-28 19:28 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +        windowMenu.setMnemonic(KeyEvent.VK_X);
Нет ответа! Напоминаю о правилах хорошего тона

2024-02-28 19:28 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +        menuBar.add(windowMenu);
Нет ответа

2024-02-28 19:33 UTC, vpyzhyanov commented
Можете мёрджить. Вот только снял у вас 1 балл за отсутствие ответов на вопросы. С каждой следующей задаче за такое буду снижать всё больше и больше

2024-02-29 02:06 UTC, merged