Теперь окна сохраняют своё состояние
AHDEPCEH/Robots_JavaProject pull request #2
Opened 2024-03-25 18:53 UTC by AHDEPCEH

Добавил классы и методы для сохранения состояния окон в файл

2024-03-28 05:12 UTC, vpyzhyanov requested changes
есть замечания

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/GameWindow.java
> +        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
то есть каждое окно управляет **ГЛОБАЛЬНЫМ** состоянием закрытия приложения? Срочно убрать!

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/GameWindow.java
> +                dispose();
не знаю зачем вам это надо. Если вызывать dispose у родителя, то это уничтожит и дочерние окна тоже

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +        addWindow(new LogWindow(Logger.getDefaultLogSource(), fileManager));
Нет смысла передавать `LogWindowSource` в конструкторе. Это статический публичный класс.

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/RobotsProgram.java
> +      } catch (Exception ignored) {}
на каком основании сделано это изменение? Вы правда хотите ощутить мучительную боль от непонимания что происходит в случае ошибки, которую вы не можете увидеть? Поверьте, вам это не надо

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/RobotsProgram.java
> +        MainApplicationFrame frame = new MainApplicationFrame(System.getProperty("user.home")+"/save");
нарушение ООП. Класс лезет не в своё дело. За файлы и тем более за место для сохранение состояния отвечает совсем другой класс.

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +public class FileManager {
Название и описание не соответствуют действительности. Ответственность класса вообще не про это. Вы вводите в заблуждение. Попробуйте конкретизировать цель этого класса.

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +        } catch (IOException ignored) {}
Вы зарядили пистолет и направили себе в ногу. Он выстрелит когда произойдёт ошибка. Может не стоит так делать? Больно же будет?!

> на каком основании сделано это изменение? Вы правда хотите ощутить мучительную боль от непонимания что происходит в случае ошибки, которую вы не можете увидеть? Поверьте, вам это не надо

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +        } catch (IOException ignored) {}
на каком основании сделано это изменение? Вы правда хотите ощутить мучительную боль от непонимания что происходит в случае ошибки, которую вы не можете увидеть? Поверьте, вам это не надо

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +        BufferedReader reader = new BufferedReader(new FileReader(fileName));
некорректная работа с потоками вввода/вывода

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/Saver.java
> +        if (window instanceof JFrame) state.put("state", Integer.toString(((JFrame) window).getExtendedState()));
хотите стать мастером однострочного программирования? Тогда пишите методы целиком в одну строчку

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/Saver.java
> +        if (window instanceof JInternalFrame) state.put("icon", Boolean.toString(((JInternalFrame) window).isIcon()));
хотите стать мастером однострочного программирования? Тогда пишите методы целиком в одну строчку

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/Saver.java
> +        if (window instanceof JFrame) ((JFrame) window).setExtendedState(Integer.parseInt(state.get("state")));
хотите стать мастером однострочного программирования? Тогда пишите методы целиком в одну строчку

2024-03-28 05:12 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/Saver.java
> +        if (window instanceof JInternalFrame) ((JInternalFrame) window).setIcon(Boolean.parseBoolean(state.get("icon")));
хотите стать мастером однострочного программирования? Тогда пишите методы целиком в одну строчку

2024-03-29 19:06 UTC, AHDEPCEH commented
Я отформатировал код и вернул обратно вывод ошибок в терминал. Но я не успел сегодня поработать с чтением и записью в файл, а вернее над тем, как идёт процесс сохранения состояния окон. Также я хотел у вас спросить, я правильно понимаю, что я у меня не верна сама идея сохранения состояний? Мне нужно разом читать и записывать весь файл?
Мне нужно хранить в памяти словарь, который будет дублировать файл и из которого я буду читать, а потом его и изменять и разом записывать? - Такая реализация более правильная, с точки зрения быстроты выполнения кода и безопасности?
Если это не лучший способ, то не могли бы вы мне дать совет как лучше реализовать работу с файлами?

2024-03-29 19:09 UTC, AHDEPCEH commented on src/main/java/ru/urfu/gui/GameWindow.java
> +        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
Я правильно понимаю, что тут проблема заключается в том, что внутренние окна не долны иметь доступ к файловому менеджеру?
Если да, тогда получается, что главное окно должно восстанавливать состояние внутренних окон, а также запрашивать сохранение состояния?

2024-03-31 19:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/GameWindow.java
> +        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
Нет, неправильно. Замечание не об этом. Хотя если вы спрашиваете про **файловый** менеджер, то зачем вообще графическим компонентам **файловый** менеджер? Их задача рисовать элементы интерфейса и всё.

Посмотрите к какой строчке написано замечание. Это строка 28: `setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);`. Ознакомьтесь, пожалуйста, что это за метод и что он делает. Замечание именно про него.

2024-03-31 20:04 UTC, vpyzhyanov commented
> Я отформатировал код и вернул обратно вывод ошибок в терминал. Но я не успел сегодня поработать с чтением и записью в файл, а вернее над тем, как идёт процесс сохранения состояния окон. Также я хотел у вас спросить, я правильно понимаю, что я у меня не верна сама идея сохранения состояний? Мне нужно разом читать и записывать весь файл? 

Если мы говорим о легко поддерживаемых и производительных приложениях, то да, файл записывать нужно разом.

> Мне нужно хранить в памяти словарь, который будет дублировать файл и из которого я буду читать, а потом его и изменять и разом записывать?

Мне кажется вы некорректно употребили слово "дублировать". Дублировать это так "`Мне кажется вы некорректно употребили слово "дублировать"`". А читать из файла информацию - это не дублирование.

Ещё в этой фразе меня смущает процесс, который вы хотите сделать с информацией из файла. Можно подумать, что ваша цель - редактирование файла, но это не так. Ваша цель - сохранить и восстановить состояние окон. Эти операции делаются в сильно разный момент времени и файл - это только место хранения, а не сама цель. Думайте о состоянии, а не о файле.

> не могли бы вы мне дать совет как лучше реализовать работу с файлами?

правильный вопрос должен содержать слова "работу с **состояниями**".

- Каждая компонента должна уметь отдавать и принимать состояние
- Менеджер состояний должен уметь взять состояние у каждой компоненты и сохранить его (и наоборот восстановить состояние, т.е. отдать состояние каждой компоненте)
- В идеале про "файл" должен знать только менеджер состояний
- И ещё один важный момент: нет никакого смысла хранить состояние в памяти на протяжении работы приложения. Оно нужно только в самом начале и в самом конце, при закрытии

2024-04-16 18:42 UTC, vpyzhyanov requested changes
Как исправите замечания, можете мёрджить

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +                savableFrames.add(window);
если вы в любой (такой момент наступает всего один раз в жизни приложения) момент можете сформировать список сохраняемых компонент, то зачем их сохранять в поле?? Незачем

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +    private final List<Container> savableFrames = new ArrayList<>();
лишнее поле. Только память занимает, а пользы не приносит

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +            StateManager.saveAllStates(savableFrames, fileManager);
fileManager нужен только для StateManager. Следовательно он должен быть внутри StateManager и никто про него знать не должен (привет инкапсуляции)!

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/MainApplicationFrame.java
> +            e.printStackTrace();
прошу всегда писать человекочитаемое сообщение об ошибке. Стек - это хорошо, пригодится, но дополнительно нужно написать понятный пользователю текст

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/RobotsProgram.java
> +          e.printStackTrace();
аналогично

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +public class FileManager {
Поправили описание - это очень хорошо. Но забыли переименовать класс, имя класса описанию сейчас не соответствует.

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/FileManager.java
> +            e.printStackTrace();
аналогично

2024-04-16 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/saveUtil/StateManager.java
> +        if (window instanceof JFrame) {
учитесь писать модно и молодёжно

```
        if (window instanceof JFrame frame) {
                state.put("state", Integer.toString(frame.getExtendedState()));
        }
```

2024-04-19 14:19 UTC, merged