Task3
AHDEPCEH/Robots_JavaProject pull request #3
Opened 2024-04-09 09:51 UTC by AHDEPCEH

2024-04-21 14:16 UTC, vpyzhyanov requested changes
Есть замечания

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/CoordinateWindow.java
> +            e.printStackTrace();
я уже не один раз писал замечание про то, что надо делать человекочитаемые сообщения об ошибке, это же не сложно

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/GameVisualizer.java
Зачем удалили? С какой целью?

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/gui/GameWindow.java
> +public class GameWindow extends JInternalFrame implements Savable
что тут делают изменения из второй задачи? Обратите внимание, что у вас конфликт, вы не можете смёрджить пока его не разрешите. Ну и это влияет на эти изменения. Вам необходимо сделать merge ветки main в task3

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/robot/RobotModel.java
> +        supporter.firePropertyChange("property", (double) m_targetPositionY, p.y);
не надо кучи событий на каждую координату. Достаточно одного события изменения **модели**, все изменившиеся данные содержатся в ней

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/robot/RobotModel.java
> +            supporter.firePropertyChange("angle", (int) angleToTarget, (int) newAngle);
не надо кучи событий на каждую координату

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/robot/Visualizer.java
> +package ru.urfu.robot;
Не согласен! Эта панель - часть gui, поэтому я категорически не согласен с тем, что вы её от туда перенесли. Нехорошо нарушать структуру пакетов класса.

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/robot/Visualizer.java
> +    private double robotDirection = 0;
дублирование данных. Да и непонятно зачем, ведь у вас есть модель. В MVC модель служит источником данных и нужна как раз для того, чтобы не дублировать код. Удаляйте эти поля

2024-04-21 14:16 UTC, vpyzhyanov commented on src/main/java/ru/urfu/robot/Visualizer.java
> +        robotPositionX = model.getRobotPositionX();
не надо ничего копировать, это лишние действия

2024-04-21 15:14 UTC, AHDEPCEH commented on src/main/java/ru/urfu/gui/GameVisualizer.java
Удалил, так как за место него создал другой класс(почти что переименовал)

2024-05-05 10:55 UTC, vpyzhyanov approved these changes
Хорошо, можете мёрджить

2024-05-06 15:51 UTC, merged